{%- raw -%}
{% load_yaml as lookup %}
FreeBSD:
    package: {{name}}
    service: {{name}}
Debian:
    package: {{name}}
    service: {{name}}
CentOS:
    package: {{name}}
    service: {{name}}
default:
    package: {{name}}
    service: {{name}}
{% endload %}

{% load_yaml as rawmap %}
{% endload %}
{%- endraw -%}

